// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/thelark/entgo-graphql-todo/ent/todo"
)

type TodoInput struct {
	Status   todo.Status `json:"status"`
	Priority *int        `json:"priority"`
	Text     string      `json:"text"`
	Parent   *int        `json:"parent"`
}
